version: '3'

services:
  web:
    container_name: book_list_web_container
    build: 
      context: ./web
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    ports:
        - "8088:80"
    volumes:
      - type: bind
        source: ../app
        target: /var/www/html
    networks:
      - book_list_network
  db:
    container_name: book_list_php_db_container
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - book_list_network
    volumes:
      - type: volume
        source: book_list_db_volume
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on

networks:
  book_list_network:

volumes:
  book_list_db_volume:
    driver: local